version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    networks:
      - wbes-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - wbes-network
    depends_on:
      - server
    restart: unless-stopped

networks:
  wbes-network:
    driver: bridge
